FROM registry.access.redhat.com/ubi9/openjdk-21:1.21 as builder

WORKDIR /app
COPY --chown=185:0 . .
RUN ./mvnw package

FROM registry.access.redhat.com/ubi9/openjdk-21:1.21 as runner

ENV LANGUAGE='en_US:en'

WORKDIR /opt/amaral-software/storaged-products/

COPY --from=builder --chown=185 /app/target/quarkus-app/lib /opt/amaral-software/storaged-products/lib/
COPY --from=builder --chown=185 /app/target/quarkus-app/*.jar /opt/amaral-software/storaged-products/
COPY --from=builder --chown=185 /app/target/quarkus-app/app/ /opt/amaral-software/storaged-products/app/
COPY --from=builder --chown=185 /app/target/quarkus-app/quarkus/ /opt/amaral-software/storaged-products/quarkus/
COPY --from=builder --chown=185 /app/bin/ /opt/amaral-software/storaged-products/bin/

RUN chmod +x /opt/amaral-software/storaged-products/bin/start.sh

EXPOSE 8080
USER 185

ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/opt/amaral-software/storaged-products/quarkus-run.jar"

ENTRYPOINT ["/opt/amaral-software/storaged-products/bin/start.sh"]